name: Sync-Issue-ADO

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync GH Issue
    steps:       
    - uses: danhellem/github-actions-issue-to-work-item@master
      env:     
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
        ado_project: '${{ secrets.ADO_PROJECT }}'
        ado_wit: 'Bug' 
        ado_new_state: 'New'
        ado_close_state: 'Closed'
        ado_active_state: 'Active'  
        ado_bypassrules: true